package tool

// 根据信息码返回对应的msg
func GetErrMsgByInfoCode(infoCode string)(string){
	switch infoCode {
	case "10000":
		return "OK"
	case "10001":
		return "key不正确或过期"
	case "10002":
		return "没有权限使用相应的服务或者请求接口的路径拼写错误"
	case "10003":
		return "访问已超出日访问量"
	case "10004":
		return "单位时间内访问过于频繁"
	case "10005":
		return "IP白名单出错，发送请求的服务器IP不在IP白名单内"
	case "10006":
		return "绑定域名无效"
	case "10007":
		return "数字签名未通过验证"
	case "10008":
		return "MD5安全码未通过验证"
	case "10009":
		return "请求key与绑定平台不符"
	case "10010":
		return "IP访问超限"
	case "10011":
		return "服务不支持https请求"
	case "10012":
		return "权限不足，服务请求被拒绝"
	case "10013":
		return "Key被删除"
	case "10014":
		return "云图服务QPS超限"
	case "10015":
		return "受单机QPS限流限制"
	case "10016":
		return "服务器负载过高"
	case "10017":
		return "所请求的资源不可用"
	case "10019":
		return "使用的某个服务总QPS超限"
	case "10020":
		return "某个Key使用某个服务接口QPS超出限制"
	case "10021":
		return "来自于同一IP的访问，使用某个服务QPS超出限制"
	case "10022":
		return "某个Key，来自于同一IP的访问，使用某个服务QPS超出限制"
	case "10023":
		return "某个KeyQPS超出限制"
	case "20000":
		return "请求参数非法"
	case "20001":
		return "缺少必填参数"
	case "20002":
		return "请求协议非法"
	case "20003":
		return "其他未知错误"
	case "20800":
		return "规划点（包括起点、终点、途经点）不在中国陆地范围内"
	case "20801":
		return "划点（起点、终点、途经点）附近搜不到路"
	case "20802":
		return "路线计算失败，通常是由于道路连通关系导致"
	case "20803":
		return "起点终点距离过长。"
	case "300**":
		return "服务响应失败。"
	}
	return ""
}

func GetErrMsgByInfo(infoCode string)(string){
	switch infoCode {
	//case "INVALID_USER_KEY":
	//	return "OK"
	case "INVALID_USER_KEY":
		return "key不正确或过期"
	case "SERVICE_NOT_AVAILABLE":
		return "没有权限使用相应的服务或者请求接口的路径拼写错误"
	case "DAILY_QUERY_OVER_LIMIT":
		return "访问已超出日访问量"
	case "ACCESS_TOO_FREQUENT":
		return "单位时间内访问过于频繁"
	case "INVALID_USER_IP":
		return "IP白名单出错，发送请求的服务器IP不在IP白名单内"
	case "INVALID_USER_DOMAIN":
		return "绑定域名无效"
	case "INVALID_USER_SIGNATURE":
		return "数字签名未通过验证"
	case "INVALID_USER_SCODE":
		return "MD5安全码未通过验证"
	case "USERKEY_PLAT_NOMATCH":
		return "请求key与绑定平台不符"
	case "IP_QUERY_OVER_LIMIT":
		return "IP访问超限"
	case "NOT_SUPPORT_HTTPS":
		return "服务不支持https请求"
	case "INSUFFICIENT_PRIVILEGES":
		return "权限不足，服务请求被拒绝"
	case "USER_KEY_RECYCLED":
		return "Key被删除"
	case "QPS_HAS_EXCEEDED_THE_LIMIT":
		return "云图服务QPS超限"
	case "GATEWAY_TIMEOUT":
		return "受单机QPS限流限制"
	case "SERVER_IS_BUSY":
		return "服务器负载过高"
	case "RESOURCE_UNAVAILABLE":
		return "所请求的资源不可用"
	case "CQPS_HAS_EXCEEDED_THE_LIMIT":
		return "使用的某个服务总QPS超限"
	case "CKQPS_HAS_EXCEEDED_THE_LIMIT":
		return "某个Key使用某个服务接口QPS超出限制"
	case "CIQPS_HAS_EXCEEDED_THE_LIMIT":
		return "来自于同一IP的访问，使用某个服务QPS超出限制"
	case "CIKQPS_HAS_EXCEEDED_THE_LIMIT":
		return "某个Key，来自于同一IP的访问，使用某个服务QPS超出限制"
	case "KQPS_HAS_EXCEEDED_THE_LIMIT":
		return "某个KeyQPS超出限制"
	case "INVALID_PARAMS":
		return "请求参数非法"
	case "MISSING_REQUIRED_PARAMS":
		return "缺少必填参数"
	case "ILLEGAL_REQUEST":
		return "请求协议非法"
	case "UNKNOWN_ERROR":
		return "其他未知错误"
	case "OUT_OF_SERVICE":
		return "规划点（包括起点、终点、途经点）不在中国陆地范围内"
	case "NO_ROADS_NEARBY":
		return "划点（起点、终点、途经点）附近搜不到路"
	case "ROUTE_FAIL":
		return "路线计算失败，通常是由于道路连通关系导致"
	case "OVER_DIRECTION_RANGE":
		return "起点终点距离过长。"
	case "ENGINE_RESPONSE_DATA_ERROR":
		return "服务响应失败。"
	}
	return ""
}